odoo:
  image: virgiliosantos/bradoo-odoo-community
  ports:
    - "8069:8069"
  links:
    - db
db:
  image: akretion/voodoo-postgresql
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
