services:
    odoo:
        image: virgiliosantos/bradoo-odoo-enterprise-pip
        ports:
            - "8069:8069"
        links:
            - db
    db:
      image: postgres
      environment:
        - POSTGRES_USER=odoo
        - POSTGRES_PASSWORD=odoo
version: '2'
