name: Bradoo Odoo Community 
description: |
        Simple Odoo Community with Localization addons, and buildout based 
version: 0.1-bradoo
category: Bradoo Odoo
maintainer: Bradoo Tech (virgilio.santos@bradootech.com)
license: 
projectURL: https://github.com/virgilio-bradoo/rancher-cattle-test
