name: Bradoo Enterprise Ready (pip)
description: |
        Bradoo Odoo full installed with enterprise addons
version: 0.0.1
category: Bradoo Odoo Enterprise 
maintainer: Virgilio Santos <virgilio.santos@bradootech.com>
license: MIT
projectURL: https://github.com/virgilio-bradoo/rancher-cattle-test
